version: '3'

services:
  backend:
    build:
      context: . 
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=database
    depends_on:
      - database
      
  backend-test:
    build:
      context: . 
      dockerfile: ./apps/api/Dockerfile
    environment:
      - NODE_ENV=test
    command: yarn test
    depends_on:
      - database

  database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: backend-nestjs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
